data:
  class_path: src.data.mnist_datamodule.MNISTDataModule
  data_dir: /workspace/data/
model:
  class_path: src.models.mnist_module.MNISTLitModule
  init_args:
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        _partial_: true
        lr: 0.001
        weight_decay: 0.0
    scheduler:
      class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
      init_args:
        _partial_: true
        mode: min
        factor: 0.1
        patience: 10
    net:
      class_path: src.models.components.simple_dense_net.SimpleDenseNet
