model:
  class_path: src.models.mnist_module.MNISTLitModule
  init_args:
    net: src.models.components.simple_dense_net.SimpleDenseNet
    # scheduler: torch.optim.lr_scheduler.StepLR
    # optimizer: torch.optim.Adam  dependencyのため、事前にインスタンス化できない
data:
  class_path: src.data.mnist_datamodule.MNISTDataModule
  init_args:
    data_dir: /workspace/data/
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      save_dir: ./logs/mlflow/mlruns
  max_epochs: 2
