model:
  class_path: src.models.picture_module.PictureModule
  init_args:
    lr: 1e-3
    step_size: 8
    net:
      class_path: src.models.components.picture_net.PictureNet
      # init_args:
      #   backbone: src.models.components.backbone.AlexNet
      #     init_args:
      #       out_sch: 16      # recursiveにインスタンス化できない
    scheduler: torch.optim.lr_scheduler.StepLR
    # optimizer: torch.optim.Adam
data:
  class_path: src.data.picture_datamodule.PictureDataModule
  init_args:   # transformはrecursiveになるのでここには書かない。dataloaderを読み込む手前でデータセットの作成&データ拡張やるのがいいと思うが重い
    train_dataset: 
      class_path: src.data.components.picture_data.PictureDataset
      init_args:
        mode: "train"
    val_dataset:
      class_path: src.data.components.picture_data.PictureDataset
      init_args:
        mode: "validation"
    batch_size: 16
trainer:
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      save_dir: ./logs/mlflow/mlruns
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: "val/loss"
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
#    - class_path: lightning.pytorch.callbacks.DeviceStatsMonitor
    - class_path: src.callbacks.save_images.SaveImages
      init_args:
        num_samples: 4
        nrow: 8
        padding: 2
        normalize: True
        scale_each: False
        pad_value: 0
  # profiler:
  #   class_path: lightning.pytorch.profilers.PyTorchProfiler  何故かエラーが出る
  #   init_args:
  #     emit_nvtx: True
  max_epochs: 15
  accelerator: gpu
  devices: 1
