model:
  class_path: src.models.picture_module.PictureModule
  init_args:
    net: src.models.components.picture_net.PictureNet
    scheduler: torch.optim.lr_scheduler.StepLR
    # optimizer: torch.optim.Adam
data:
  class_path: src.data.picture_datamodule.PictureDataModule
  init_args:
    train_dataset: 
      class_path: src.data.components.picture_data.PictureDataset
      init_args:
        mode: "train"
    val_dataset:
      class_path: src.data.components.picture_data.PictureDataset
      init_args:
        mode: "validation"
    batch_size: 2
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      save_dir: ./logs/mlflow/mlruns
  callbacks:
    class_path: src.callbacks.save_images.SaveImages
    init_args:
      num_samples: 4
      nrow: 8
      padding: 2
      normalize: True
      scale_each: False
      pad_value: 0
  max_epochs: 2
  accelerator: gpu
  devices: 1
